const CONFIG = {
  API_BASE_URL: import.meta.env.VITE_API_BASE_URL,
  KAKAO_REST_API_KEY: import.meta.env.VITE_KAKAO_REST_API_KEY,
  KAKAO_REDIRECT_URL: import.meta.env.VITE_KAKAO_REDIRECT_URL,
  HOLIDAYS_API_BASE_URL: import.meta.env.VITE_HOLIDAYS_API_BASE_URL,
  HOLIDAYS_SERVICE_KEY: import.meta.env.VITE_HOLIDAYS_SERVICE_KEY,
};

export default CONFIG;
