FROM node:20.11.0-alpine AS build

WORKDIR /app

ARG VITE_API_BASE_URL
ARG VITE_KAKAO_REST_API_KEY
ARG VITE_KAKAO_REDIRECT_URL

COPY package.json yarn.lock ./

COPY packages/client/package.json packages/client/
COPY packages/common-types ./packages/common-types/

RUN yarn install

COPY packages/client ./packages/client

RUN VITE_API_BASE_URL=$VITE_API_BASE_URL \
    VITE_KAKAO_REST_API_KEY=$VITE_KAKAO_REST_API_KEY \
    VITE_KAKAO_REDIRECT_URL=$VITE_KAKAO_REDIRECT_URL \
    yarn build

FROM nginx:alpine

COPY packages/client/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
ENTRYPOINT [ "nginx" ]
CMD ["-g", "daemon off;"]
