FROM node:alpine AS build

WORKDIR /app

COPY .yarn ./
COPY .yarnrc.yml ./
COPY yarn.lock ./
COPY package.json ./
COPY packages/common-types/package.json ./packages/common-types/
COPY packages/server/package.json ./packages/server/

RUN apk add --no-cache curl bash
RUN corepack enable
RUN yarn set version 4.5.0
RUN yarn cache clean
RUN yarn install

COPY ./ ./

RUN yarn server:build

FROM node:alpine AS production

WORKDIR /app

COPY package.json ./
COPY yarn.lock ./
COPY packages/common-types/package.json ./packages/common-types/
COPY packages/server/package.json ./packages/server/

RUN apk add --no-cache curl bash
RUN corepack enable && corepack prepare yarn@4.4.0 --activate
RUN yarn install

COPY --from=build /app/packages/server/dist ./packages/server/dist

ENV DB_HOST=$DB_HOST \
    DB_PORT=$DB_PORT \
    DB_USER=$DB_USER \
    DB_PASSWORD=$DB_PASSWORD \
    DB_NAME=$DB_NAME \
    REDIS_HOST=$REDIS_HOST \
    REDIS_PORT=$REDIS_PORT \
    COOKIE_SECRET=$COOKIE_SECRET \
    JWT_SECRET=$JWT_SECRET \
    KAKAO_REST_API_KEY=$KAKAO_REST_API_KEY \
    KAKAO_REDIRECT_URL=$KAKAO_REDIRECT_URL \
    BCRYPT_SALT_ROUNDS=$BCRYPT_SALT_ROUNDS

RUN npm install -g pm2

ENTRYPOINT ["yarn"]
CMD ["server:start"]
