FROM node:alpine AS build

WORKDIR /app

ARG VITE_API_BASE_URL
ARG VITE_KAKAO_REST_API_KEY
ARG VITE_KAKAO_REDIRECT_URL

COPY package.json ./
COPY yarn.lock ./
COPY packages/common-types/package.json ./packages/common-types/
COPY packages/client/package.json ./packages/client/

RUN apk add --no-cache curl bash
RUN corepack enable
RUN corepack prepare yarn@4.4.0 --activate
RUN yarn install

COPY ./ ./

RUN VITE_API_BASE_URL=$VITE_API_BASE_URL \
    VITE_KAKAO_REST_API_KEY=$VITE_KAKAO_REST_API_KEY \
    VITE_KAKAO_REDIRECT_URL=$VITE_KAKAO_REDIRECT_URL \
    yarn client:build

FROM nginx:alpine

COPY packages/client/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/packages/client/dist /usr/share/nginx/html

EXPOSE 80
ENTRYPOINT [ "nginx" ]
CMD ["-g", "daemon off;"]
